setChartTitle('Data Monitor and Alert System');
$("#muliple_graph_span").append("<h2 style=background-color:#f1ffe7;color:#0000ff><u>Temperature Graph</u><h2>");
var Graph1 = new boltGraph();
Graph1.setChartType("lineGraph");
Graph1.setAxisName('Time-->','Temperature-->');
Graph1.plotChart('time_stamp','temp');
$("#muliple_graph_span").append("<hr style=border-width:7><h2 style=background-color:#f1ffe7;color:#0000ff><u>Humidity Graph</u><h2>");
var Graph2 = new boltGraph();
Graph2.setChartType("lineGraph");
Graph2.setAxisName('Time-->','Humidity-->');
Graph2.plotChart('time_stamp','hum');
$("#muliple_graph_span").append("<hr style=border-width:7><h2 style=background-color:#f1ffe7;color:#0000ff><u>Air Quality Concentration Graph</u><h2>");
var Graph3 = new boltGraph();
Graph3.setChartType("lineGraph");
Graph3.setAxisName('Time-->','Air Quality-->');
Graph3.plotChart('time_stamp','airq');
$("#muliple_graph_span").append("<hr style=border-width:7><h2 style=background-color:#f1ffe7;color:#0000ff><u>LPG Concentration Graph</u><h2>");
var Graph4 = new boltGraph();
Graph4.setChartType("lineGraph");
Graph4.setAxisName('Time-->','LPG-->');
Graph4.plotChart('time_stamp','lpg');
$("#muliple_graph_span").append("<hr style=border-width:7><h2 style=background-color:#f1ffe7;color:#0000ff><u>Carbon Monoxide Concentration Graph</u><h2>");
var Graph5 = new boltGraph();
Graph5.setChartType("lineGraph");
Graph5.setAxisName('Time-->','Carbon Monoxide-->');
Graph5.plotChart('time_stamp','cbm');
$("#muliple_graph_span").append("<hr style=border-width:7><h2 style=background-color:#f1ffe7;color:#0000ff><u>Smoke Concentration Graph</u><h2>");
var Graph6 = new boltGraph();
Graph6.setChartType("lineGraph");
Graph6.setAxisName('Time-->','Smoke-->');
Graph6.plotChart('time_stamp','smoke');
$("#muliple_graph_span").append("<br><br><hr style=border-width:7><h4 style=background-color:#f1ffe7;width:85%>Threshold values can be changed temporarily using the link given below (Connect to same access point of ESP8266)<h4>");
let btn = document.createElement("button");
btn.innerHTML = "Go to Web Server";
btn.onclick = function () {
   window.location.href='http://192.168.217.47';
};
document.body.appendChild(btn);
$("#muliple_graph_span").append(btn);
$("#muliple_graph_span").append("<h6 style=text-align:right> Designed by Sreejak Bhuniya</h6><hr style=border-width:7>");